export const REGISTER_SUCCESS_FAN = "REGISTER_SUCCESS_FAN";
export const REGISTER_SUCCESS_TALENT = "REGISTER_SUCCESS_TALENT";
export const REGISTER_FAIL_FAN = "REGISTER_FAIL_FAN";
export const REGISTER_FAIL_TALENT = "REGISTER_FAIL_TALENT";
export const LOGOUT = "LOGOUT";
